dbtlearn:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kg94819.central-india.azure
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DEV_ROLE') }}"
      database: AIRBNB
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: null
    prod:
      type: snowflake
      account: kg94819.central-india.azure
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'PROD_ROLE') }}"
      database: AIRBNB
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: null